name: GravityFalls
version: '${version}'
main: hub.thespace.gravityfalls.GravityFalls
loadbefore: [ ProtocolLib ]
depend: [ ProtocolLib ]
commands:
  gravity:
    description: Изменяет гравитацию в мире.
    usage: "/gravity <value> <world>"
    permission: gravity.change
